[[templates]]
name = "团队访谈问答"
prompt = """
请根据转写 Markdown 输出结构化中文总结文档，输出结果仍然为Markdown格式。

注意事项：
1. 使用场景：这是VC投资机构内部使用的访谈会议纪要，注意基础的格式要求
2. 基本格式：访谈是以问答形式展开，根据转写文本，按照Q&A的形式进行总结，严格遵循转写文本，不做额外引申与发散；"""

[[templates]]
name = "客户访谈"
prompt = """
我是一家VC投资机构的投资经理，这是我对正在考察的公司的客户进行的访谈，以此来了解公司的业务进展情况。
根据会议记录为我整理一份会议纪要，需要包括以下内容：
1. 双方合作情况概要：包括合作背景、合作目标、合作进展
2. 客户自身业务情况介绍
3. 公司产品及业务详细使用情况与评价
4. 公司产品、业务上是否有需要提升的地方
5. 是否对比过公司与其他竞品的产品，对比结果如何。
6. 未来是否会扩大与公司的合作。
注意：以上内容严格根据会议记录内容总结，不额外发散、引申，对于会议记录中没有涉及的内容，客观总结补充"""

[[templates]]
name = "通用模板"
prompt = """
请根据转写 Markdown 输出结构化中文总结文档，输出结果仍然为Markdown格式。
如果文本中有大段介绍内容，单独总结呈现；如果有Q&A部分，按照Q&A的模板，针对每个问题做总结呈现。

注意事项：
1. 严格遵循转写文本，不擅自增加虚假信息；
2. 对于可能的转写错误字词和可能的正确词语在输出文档前进行列示；
3. 根据转写内容，总结其中包括哪些主题，按照主题-内容的形式进行总结"""

[[templates]]
name = "首次交流模板"
prompt = """
我是一家VC投资机构的投资经理，这是我与公司首次交流时，公司路演介绍自身公司及业务，并与我进行讨论的会议记录。
根据会议记录为我整理一份会议纪要，需要包括以下内容：
公司核心团队背景；
行业信息：包括市场规模、主要玩家，当前头部玩家，发展趋势等；
公司产品情况：包括业务与产品介绍，底层技术细节，产品研发进展，商业模式等；
公司业务进展：包括业务开展进度，核心里程碑达成情况，关键运营指标等；
未来发展策略：公司未来在产品增长、商业化等方向的发展规划。
公司融资情况：包括历史融资情况，当前融资规划.
注意：以上内容严格根据会议记录内容总结，不额外发散、引申，对于会议记录中没有涉及的内容，客观指出即可。
遵循Markdown语法规范。"""
